### ISSUE TITLE
Problem on windows while using Cygwin64 bash

### ISSUE THREAD

**Issue by TheLeoP** [nikvdp/neomux#15]
I'm trying to use this plugin on windows using Cygwin64 bash, but all the commands (bash scripts) gave me the following error for each line of the script.

```
/cygdrive/c/Users/pcx/AppData/Local/nvim-data/site/pack/packer/start/neomux/plugin/bin/s: line 2: $'\r': command not found
```

I guess that's happening because end of lines have different encoding for Windows and Linux. So, is it possible to give support for windows? At least while using Cygwin.

EDIT: Ok, so I found out that setting an enviroment variable called `SHELLOPTS` to `igncr` makes cygwin ignore the `\r` at the end of the line. But, since the command `uname -s` inside cygiwn bash returns `CYGWIN_NT-10.0`, and not `Darwin` nor `Linux`, the script `nvm` is never added to tha path and any command returns `/cygdrive/c/Users/pcx/AppData/Local/nvim-data/site/pack/packer/start/neomux/plugin/bin/funcs.sh: line 8: nvr: command not found
`

**Comment by nikvdp** [comment]
Hey @TheLeoP! Well that one's definitely a new combination. The `nvr` binary that comes bundled with the repo is a Linux binary that won't work directly under Cygwin, but if you can install python3 in your Cygwin environment you should be able to do `pip install neovim-remote` and neomux should work fine after that. Let me know if that does the trick!

**Comment by TheLeoP** [comment]
Yup, that did the trick. Now I'm able to use neomux normally. Thanks c:
