### ISSUE TITLE
Bug: Not working

### ISSUE THREAD

**Issue by raguay** [nikvdp/neomux#20]
Hi,

I run neovim nightly with LazyVim neovim configuration. I loaded the extension and it will open a terminal, but there are none of the terminal commands available. I also don't have the status bar showing window numbers.

**Comment by nikvdp** [comment]
Hi @raguay, sounds like the plugin is not getting loaded. If you run `:echo g:neomux_loaded` does it print `1` in the status bar?

**Comment by nikvdp** [comment]
Closing this for now as this is most likely not an issue with neomux itself but please feel re-open if the command above does indeed print a `1` and the neomux commands aren't present

**Comment by raguay** [comment]
> Hi @raguay, sounds like the plugin is not getting loaded. If you run `:echo g:neomux_loaded` does it print `1` in the status bar?

I'm using LazyVim and it shows it in the loaded extensions list.
