### ISSUE TITLE
Overriding Airline information

### ISSUE THREAD

**Issue by basmoura** [nikvdp/neomux#5]
Hey! Thanks for the plugin!

I'm having an issue with neomux and vim-airline. When I start my elixir project thats how my airline looks like

![image](https://user-images.githubusercontent.com/3411986/94699075-50822a80-0310-11eb-917a-7afde0edfc46.png)

and before add neomux thats how my airline looks like

![image](https://user-images.githubusercontent.com/3411986/94699327-95a65c80-0310-11eb-8b9a-f6a39496780c.png)

how can I merge all those informations?

**Comment by nikvdp** [comment]
Hey @basmoura, glad to hear from you! Just took a look, looks like I wasn't using the officially blessed method of integrating with airline. I've reworked it in this commit (https://github.com/nikvdp/neomux/commit/4b78a630f186a1da63f1f19d20a014702e9e083f), please try pulling and let me know if that fixes it.

Closing the issue as I'm pretty the bad airline integration code was the problem, but please re-open if you're still getting the same behavior on the latest version!

**Comment by basmoura** [comment]
hey @nikvdp thank you for your answer! Just to let you know, after updating to the latest version its working great with airline! Thank you!!

**Comment by nikvdp** [comment]
You bet!

**Comment by nikvdp** [comment]
Hey @basmoura just a heads up, my fix yesterday ended up causing another issue (window numbers would disappear from terminal windows after moving in and out of a term window). I've (hopefully!) fixed that one too, but you may want to pull the latest again.
